CREATE TABLE user (
id INTEGER PRIMARY KEY AUTOINCREMENT,
email VARCHAR(255) NOT NULL UNIQUE,
username VARCHAR(255) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
is_admin INTEGER DEFAULT 0,
createdAt DATETIME NOT NULL
);
